### ISSUE TITLE
Compatible with Gutenberg

### ISSUE THREAD

**Issue by khoipro** [carrieforde/Alcatraz#102]
Hi,

I think your theme is great, but we should create a way to working with Gutenberg blocks.

Some of my suggestions:

- Can override custom block styles from other Gutenberg block plugins.
- Have a less structure, focusing into header, footer, sidebar, widget.
- Improve Customizer to keep managing header, footer.

Less is better.

**Comment by carrieforde** [comment]
Aww, thanks @khoipro!

I absolutely agree that less is better when it comes to a starter theme / theme framework. Alcatraz already comes with some decent (yet could be improve) Gutenberg support. For example, I have included the color and font size palettes by default.

For your suggestions, let me see if I understand what you're suggesting:

> Can override custom block styles from other Gutenberg block plugins.

You're looking for a way to easily override / update styles from a third party plugin within the theme. You can totally do that! I don't have a good public example at the minute, but typically, when I'm styling blocks from other plugins, I'll add a new file in the `06-components` Sass folder with the class name of the block.

For example, let's say I have a carousel from a plugin, and I want to customize the styles. I'll add `_components.wp-block-my-carousel.scss` to the components folder, write my styles, and import that into the `main.scss` file.

In an effort to keep Alcatraz lean, I have opted not to style the standard editor blocks (or any blocks, for that matter) by default.

> Have a less structure, focusing into header, footer, sidebar, widget.

I think I understand this one. Instead of relying on structure coming from templates, we should use perhaps one template (e.g. `index.php`) as the main content template, which pulls in the header, footer, [maybe] sidebar, and a placeholder for the content. From there, we'll rely on the Gutenberg blocks to build out the page.

I think this is great, and I totally agree. I think we could easily get away with just `index.php` and dumping a lot of the other templates. I'm hesitant to trash too many of the `template-parts` at this time only because they are super useful for creating archive pages.

> Improve Customizer to keep managing header, footer.

I'm not sure I fully understand this one. Let me know in what ways you think the customizer experience could be improved. 😄
